TOP_STOCKS = [
    "AAPL", "NVDA", "MSFT", "AMZN", "GOOGL", "META", "BRK.B", "AVGO", "TSLA", "TSM",
    "LLY", "WMT", "JPM", "V", "XOM", "MA", "UNH", "JNJ", "PG", "CVX",
    "HD", "PFE", "ABBV", "CSCO", "PEP", "KO", "ORCL", "MRK", "INTC", "NFLX",
    "ADBE", "CRM", "DIS", "CMCSA", "NKE", "C", "ABT", "TMO", "ACN", "MDT",
    "HON", "IBM", "DHR", "AMGN", "BMY", "LMT", "QCOM", "RTX", "GS", "MS",
    "AXP", "BA", "CHTR", "INTU", "CVS", "PM", "SBUX", "MMM", "TGT", "SPGI",
    "CAT", "BKNG", "UPS", "NOW", "ANTM", "MU", "TXN", "ZTS", "CB", "CI",
    "CL", "MDLZ", "ADP", "LOW", "FISV", "USB", "DUK", "ELV", "EOG", "MMC",
    "PNC", "GILD", "SO", "REGN", "BDX", "T", "FDX", "NSC", "PGR", "SHW",
    "BLK", "D", "TRV", "AON", "APD", "CME", "PSA", "ITW", "CCI", "WM",
    "ADI", "MCD", "EQIX", "NOC", "AEP", "OXY", "ROST", "PLD", "ECL", "FANG",
    "ALL", "VLO", "MAR", "YUM", "CDNS", "EXC", "COF", "CTVA", "WELL", "GD",
    "CARR", "KMB", "SNPS", "FRC", "DFS", "WEC", "CTAS", "DG", "ROP", "IQV",
    "OTIS", "TEL", "MCK", "MNST", "IDXX", "SBAC", "PAYX", "HLT", "PCAR", "LHX",
    "TFC", "EBAY", "AIG", "VICI", "SRE", "STZ", "KEYS", "ANET", "MSCI", "SPG",
    "DLR", "AZO", "ED", "STT", "AFL", "RSG", "OKE", "TSCO", "WBA", "MTD",
    "LEN", "FAST", "AMP", "VMC", "XEL", "PPG", "FITB", "GLW", "HCA", "F",
    "AME", "FLT", "VRSK", "PEG", "GWW", "BALL", "HPQ", "DTE", "EIX", "CHD",
    "HSY", "NUE", "PXD", "HES", "LUV", "ZBH", "PH", "FTNT", "ALB", "CMS",
    "WMB", "AVB", "AKAM", "UAL", "MOS", "ES", "DLTR", "ETR", "MLM", "DOV",
    "FIS", "BAX", "ZBRA", "CNP", "EXR", "IFF", "KEY", "XYL", "CLX", "DXCM",
    "VTRS", "CINF", "RF", "TSN", "CAG", "CBRE", "LNT", "SIVB", "JBHT", "WST"
]